package: metainfo_lang_fields
version: '1.0.2'
author: 'Friends Of REDAXO'
description: 'Mehrsprachige Metainfo-Felder mit zwei Benutzeroberflächen'
license: 'MIT'
supportpage: 'https://github.com/FriendsOfREDAXO/metainfo_lang_fields'

requires:
    packages:
        metainfo: '>=2.11'
    redaxo: '^5.15'
    php:
        version: '^8.1'
